[package]
name = "rusty_dragonbones"
version = "0.3.0"
edition = "2021"
description = "DragonBones runtime for Rust"
license = "MIT"

[dependencies]
serde = {version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
tween = "2.0.4"
